// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snxgsznjpmvncsjctpkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNueGdzem5qcG12bmNzamN0cGtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMDE5MjAsImV4cCI6MjA3MzU3NzkyMH0.qBX4nYZx9FCp9Asoug_HYebrReE_HbolzhgneS80Ddo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});